FROM intel/intel-extension-for-pytorch:2.1.10-xpu 
ENV LANG=C.UTF-8

ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt update && \
    apt install -y --no-install-recommends --fix-missing \
    ffmpeg && \
    apt-get clean && \
    rm -rf  /var/lib/apt/lists/*

#ENV LD_LIBRARY_PATH=/opt/intel/oneapi/lib:/opt/intel/oneapi/lib/intel64:$LD_LIBRARY_PATH
#ENV ONEAPI_ROOT=/opt/intel/oneapi
#ENV DPCPPROOT=${ONEAPI_ROOT}/compiler/latest
#ENV MKLROOT=${ONEAPI_ROOT}/mkl/latest
# ONEDNN_LAYOUT must be 0 for whisper else it crashes (why?!?)
ENV IPEX_XPU_ONEDNN_LAYOUT=0  

#RUN . ${ONEAPI_ROOT}/setvars.sh

#RUN apt update && \
#    apt install -y sudo 

COPY poetry.lock /deps/
COPY pyproject.toml /deps/

# install an XPU patched version of OpenAI Whisper and the whisper-asr-webservice
RUN pip install poetry==1.6.1 setuptools wheel && \
	pip install --upgrade git+https://github.com/leuc/whisper.git@b4bc9b280a2db1515782e0d68a02f90cebcd438e && \
	export PATH=$PATH:/home/user/.local/bin && \
	git clone https://github.com/ahmetoner/whisper-asr-webservice.git app && \
	cd app && git checkout 51c6eceda0836d145048224693c69c2706d78f46 && \
	rm poetry.lock pyproject.toml && cp /deps/* ./ && \
	poetry config virtualenvs.create false && \
	poetry lock && poetry install --no-interaction && \
	sudo apt-get clean && \
	sudo rm -rf  /var/lib/apt/lists/*

ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:9000", "--workers", "1", "--timeout", "0", "app.webservice:app", "-k", "uvicorn.workers.UvicornWorker"]
